.bail ON
.mode columns
.headers on
.nullvalue NULL
PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS EXTRAS;
DROP TABLE IF EXISTS TIPO_VEICULO;
DROP TABLE IF EXISTS MODELO_VEICULO;
DROP TABLE IF EXISTS MARCA_VEICULO;
DROP TABLE IF EXISTS ESTADO_ATUAL;
DROP TABLE IF EXISTS TIPO_COMBUSTIVEL;
DROP TABLE IF EXISTS VEICULO;

DROP TABLE IF EXISTS TIPO_CONTRATO;
DROP TABLE IF EXISTS CATEGORIA_SALARIAL;
DROP TABLE IF EXISTS ESPECIALIZACAO;
DROP TABLE IF EXISTS POSICAO_EMPRESA;
DROP TABLE IF EXISTS CODIGO_POSTAL;
DROP TABLE IF EXISTS LOCALIDADE;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS ALUGUER;
DROP TABLE IF EXISTS TAXA_RISCO;
DROP TABLE IF EXISTS FRANQUIA;


--CREATE TABLES
CREATE TABLE EXTRAS (
	id_extras INTEGER NOT NULL PRIMARY KEY,
	Ar_condicionado BOOLEAN NOT NULL,
	Caixa_velocidades TEXT NOT NULL,
	Cruise_control BOOLEAN NOT NULL,
	Nr_portas INTEGER NOT NULL,
	Sensores_estacionamento BOOLEAN NOT NULL,
	Teto_panoramico BOOLEAN NOT NULL,
	Tipo_estofos TEXT NOT NULL,
	Vidros_eletricos BOOLEAN NOT NULL,
	UNIQUE (id_extras),
	CHECK (id_extras >= 0 AND Nr_portas >= 0)
);

CREATE TABLE TIPO_VEICULO (
	id_tipoVeiculo INTEGER NOT NULL PRIMARY KEY,
	Designacao_veiculo TEXT NOT NULL UNIQUE,
	UNIQUE (id_tipoVeiculo)
);

CREATE TABLE MODELO_VEICULO (
	idModeloVeiculo INTEGER NOT NULL PRIMARY KEY,
	Ano_producao INTEGER NOT NULL
		CHECK (Ano_producao > 1876),
	Nome_modelo TEXT NOT NULL,
	id_Marca INTEGER NOT NULL REFERENCES MARCA_VEICULO(id_Marca)
);

CREATE TABLE MARCA_VEICULO(
	id_Marca INTEGER NOT NULL PRIMARY KEY,
	Nome_marca TEXT NOT NULL UNIQUE,
	UNIQUE (id_Marca)
);

CREATE TABLE ESTADO_ATUAL(
	id_estadoAtual INTEGER NOT NULL PRIMARY KEY,
	Nome_estado TEXT NOT NULL UNIQUE,
	UNIQUE (id_estadoAtual)
);

CREATE TABLE TIPO_COMBUSTIVEL(
	id_tipoCombustivel INTEGER NOT NULL PRIMARY KEY,
	Nome_combustivel TEXT NOT NULL UNIQUE,
	UNIQUE (id_tipoCombustivel)
);

CREATE TABLE VEICULO(
	id_veiculo INTEGER NOT NULL PRIMARY KEY,
	Matricula TEXT NOT NULL,
	Consumo REAL NOT NULL
		CHECK(Consumo > 0),
	Preco_aluguer INTEGER
		CHECK(Preco_aluguer > 0),
	idModeloVeiculo INTEGER REFERENCES MODELO_VEICULO(idModeloVeiculo),
	id_estadoAtual INTEGER REFERENCES ESTADO_ATUAL(id_estadoAtual),
	id_tipoVeiculo INTEGER REFERENCES TIPO_VEICULO(id_tipoVeiculo),
	id_tipoCombustivel INTEGER REFERENCES TIPO_COMBUSTIVEL(id_tipoCombustivel),
	id_extras INTEGER REFERENCES EXTRAS(id_extras),
	UNIQUE (id_veiculo)
);

CREATE TABLE TIPO_CONTRATO(
	id_tipoContrato INTEGER NOT NULL PRIMARY KEY,
	Designacao_contrato TEXT NOT NULL UNIQUE,
		UNIQUE (id_tipoContrato)
);

CREATE TABLE CATEGORIA_SALARIAL(
	id_Categoria_Salarial INTEGER PRIMARY KEY,
	Montante INTEGER NOT NULL
		CHECK (Montante > 0),
	UNIQUE (id_Categoria_Salarial)
);

CREATE TABLE ESPECIALIZACAO(
	id_especializacao INTEGER NOT NULL PRIMARY KEY,
	Nome_especializacao TEXT NOT NULL UNIQUE,
		UNIQUE(id_especializacao)
);

CREATE TABLE POSICAO_EMPRESA(
	id_posicaoEmpresa INTEGER NOT NULL PRIMARY KEY,
	Nome_posicao TEXT NOT NULL UNIQUE,
		UNIQUE(id_posicaoEmpresa)
);

CREATE TABLE CODIGO_POSTAL(
	id_codigoPostal INTEGER NOT NULL PRIMARY KEY,
	Nome_postal TEXT UNIQUE,
		UNIQUE(id_codigoPostal)
);

CREATE TABLE LOCALIDADE(
	id_localidade INTEGER NOT NULL PRIMARY KEY,
	Nome_localidade TEXT NOT NULL UNIQUE,
		UNIQUE(id_localidade)
);

CREATE TABLE PESSOA(
	id_pessoa INTEGER NOT NULL PRIMARY KEY,
	Telefone Integer NOT NULL UNIQUE,
	Morada TEXT NOT NULL,
	Nome_pessoa TEXT NOT NULL,
	id_localidade REFERENCES LOCALIDADE(id_localidade),
	id_codigoPostal REFERENCES CODIGO_POSTAL(id_codigoPostal),
		UNIQUE(id_pessoa)
);

CREATE TABLE CLIENTE(
	id_cliente INTEGER NOT NULL PRIMARY KEY,
	NIF INTEGER NOT NULL UNIQUE,
	id_pessoa INTEGER NOT NULL,
	E_mail TEXT NOT NULL,
	FOREIGN KEY(id_pessoa) REFERENCES PESSOA(id_pessoa)
);

CREATE TABLE FUNCIONARIO(
	id_funcionario INTEGER NOT NULL PRIMARY KEY,
	NIB TEXT NOT NULL UNIQUE,
	id_pessoa INTEGER NOT NULL,
	id_tipoContrato INTEGER REFERENCES TIPO_CONTRATO(id_tipoContrato),
	id_Categoria_Salarial INTEGER REFERENCES CATEGORIA_SALARIAL(id_Categoria_Salarial),
	id_posicaoEmpresa INTEGER REFERENCES POSICAO_EMPRESA(id_posicaoEmpresa),
	id_especializacao TEXT REFERENCES ESPECIALIZACAO(id_especializacao),
	FOREIGN KEY(id_pessoa) REFERENCES PESSOA(id_pessoa),
		UNIQUE(id_funcionario)
);


CREATE TABLE ALUGUER(
	id_aluguer INTEGER NOT NULL PRIMARY KEY,
	Custo_total INTEGER NOT NULL
		CHECK (Custo_total > 0),
	Data_de_fim DATE NOT NULL,
	Data_de_inicio DATE NOT NULL CHECK (Data_de_inicio <= Data_de_fim),
	id_funcionario INTEGER NOT NULL REFERENCES FUNCIONARIO(id_funcionario),
	id_cliente INTEGER NOT NULL REFERENCES CLIENTE(id_cliente),
		UNIQUE(id_aluguer)
);


CREATE TABLE TAXA_RISCO(
	id_taxaRisco INTEGER NOT NULL UNIQUE,
	Valor_risco INTEGER NOT NULL
		CHECK(Valor_risco > 0),
	id_cliente INTEGER NOT NULL,
	id_aluguer INTEGER NOT NULL,
	FOREIGN KEY(id_cliente) REFERENCES CLIENTE(id_cliente),
	FOREIGN KEY(id_aluguer) REFERENCES ALUGUER(id_aluguer),
	PRIMARY KEY (id_taxaRisco, id_aluguer)
);


CREATE TABLE FRANQUIA(
	Valor_franquia INTEGER NOT NULL
		CHECK(Valor_franquia > 0),
	id_veiculo INTEGER NOT NULL,
	id_aluguer INTEGER NOT NULL,
	FOREIGN KEY(id_veiculo) REFERENCES VEICULO(id_veiculo),
	FOREIGN KEY(id_aluguer) REFERENCES ALUGUER(id_aluguer),
	PRIMARY KEY (id_veiculo, id_aluguer)
);